%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 3.26.6

-ifndef(hello_pb).
-define(hello_pb, true).

-define(hello_pb_gpb_version, "3.26.6").

-ifndef('PERSON_PB_H').
-define('PERSON_PB_H', true).
-record(person,
        {name                   :: binary() | iolist(), % = 1
         age                    :: integer()        % = 2, 32 bits
        }).
-endif.

-endif.
